export enum AppleWatchMetric {
  SLEEP = 'SLEEP',
  STEPS = 'STEPS',
  ACTIVE_CALORIES = 'ACTIVE_CALORIES',
  RESTING_HEART_RATE = 'RESTING_HEART_RATE',
  WATER_CONSUMPTION = 'WATER_CONSUMPTION',
  MINDFULNESS_MINUTES = 'MINDFULNESS_MINUTES',
}
