apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VictorAgahi/VaultedMind
    targetRevision: main
    path: k8s/services/backend/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
