apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: vault-backend=ghcr.io/victoragahi/vault-backend
    argocd-image-updater.argoproj.io/vault-backend.update-strategy: semver
    argocd-image-updater.argoproj.io/vault-backend.allow-tags: regexp:^[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/vault-backend.update-method: kustomize
    argocd-image-updater.argoproj.io/vault-backend.kustomize-image-name: vault-backend
spec:
  project: default
  source:
    repoURL: https://github.com/VictorAgahi/VaultedBack
    targetRevision: main
    path: k8s/services/backend/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
