apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: ms-user

images:
- name: victorcra/masterquizz-ms-user
  newName: victorcra/masterquizz-ms-user
  newTag: 65e33de6f831129b3efeff92b1e52f02793bd9e2
