apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: masterquizz-microservices
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: prod
                  namespace: masterquizz-prod
          - list:
              elements:
                - service: base
                - service: api-gateway
                - service: ms-user
                - service: ms-quizz-management
                - service: ms-session
                - service: ms-response
                - service: front-office
                - service: database
                - service: cache
                - service: messaging
                - service: monitoring
                - service: ws-service
  template:
    metadata:
      name: "{{env}}-{{service}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/MasterNIghtQuizz/head.git"
        targetRevision: HEAD
        path: "k8s/services/{{service}}/overlays/{{env}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
