apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: vault-apps
  namespace: argocd
spec:
  applicationRefs:
  - namePattern: "vault-*"
    useAnnotations: true
  commonUpdateSettings:
    updateStrategy: digest
  writeBackConfig:
    method: argocd
