apiVersion: argoproj-labs.io/v1alpha1
kind: ImageUpdater
metadata:
  name: vault-backend
  namespace: argocd
spec:
  image: ghcr.io/victoragahi/vault-backend
  registries:
  - name: ghcr
    api_url: https://ghcr.io
  template:
    metadata:
      name: vault-backend
      namespace: argocd
---
apiVersion: argoproj-labs.io/v1alpha1
kind: ImageUpdater
metadata:
  name: vault-frontend
  namespace: argocd
spec:
  image: ghcr.io/victoragahi/vault-frontend
  registries:
  - name: ghcr
    api_url: https://ghcr.io
  template:
    metadata:
      name: vault-frontend
      namespace: argocd
