apiVersion: v1
kind: Secret
metadata:
  name: vaultedback-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:VictorAgahi/VaultedBack.git
  sshPrivateKey: |
    # Cat the file content here:
    # cat ~/.ssh/vaultedback >> this file
