apiVersion: v1
kind: Service
metadata:
  name: vault-frontend
  namespace: vault-prod
spec:
  type: ClusterIP
  selector:
    app: vault-frontend
  ports:
  - port: 80
    targetPort: 3000
    name: http
