apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: victorcra/masterquizz-front-office
  newName: victorcra/masterquizz-front-office
  newTag: 82d6eda34b752e8c6189e81e7ae3fb941f1f2cd7
